<?php

namespace ContainerZxDrT0I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEgresadoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EgresadoController' shared autowired service.
     *
     * @return \App\Controller\EgresadoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EgresadoController.php';

        $container->services['App\\Controller\\EgresadoController'] = $instance = new \App\Controller\EgresadoController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\EgresadoController', $container));

        return $instance;
    }
}
