<?php

namespace ContainerZxDrT0I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/DataCollector/Proxy/ResolvedTypeFactoryDataCollectorProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/ResolvedFormTypeFactory.php';

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Form\\ArchivosOrigType' => ['privates', 'App\\Form\\ArchivosOrigType', 'getArchivosOrigTypeService', true],
            'App\\Form\\ArchivosType' => ['privates', 'App\\Form\\ArchivosType', 'getArchivosTypeService', true],
            'App\\Form\\CarrerasType' => ['privates', 'App\\Form\\CarrerasType', 'getCarrerasTypeService', true],
            'App\\Form\\DatosAcademicosOrigType' => ['privates', 'App\\Form\\DatosAcademicosOrigType', 'getDatosAcademicosOrigTypeService', true],
            'App\\Form\\DatosAcademicosType' => ['privates', 'App\\Form\\DatosAcademicosType', 'getDatosAcademicosTypeService', true],
            'App\\Form\\DatosAdministrativosOrigType' => ['privates', 'App\\Form\\DatosAdministrativosOrigType', 'getDatosAdministrativosOrigTypeService', true],
            'App\\Form\\DatosAdministrativosType' => ['privates', 'App\\Form\\DatosAdministrativosType', 'getDatosAdministrativosTypeService', true],
            'App\\Form\\DatosPersonalesOrigType' => ['privates', 'App\\Form\\DatosPersonalesOrigType', 'getDatosPersonalesOrigTypeService', true],
            'App\\Form\\DatosPersonalesType' => ['privates', 'App\\Form\\DatosPersonalesType', 'getDatosPersonalesTypeService', true],
            'App\\Form\\DocumentosType' => ['privates', 'App\\Form\\DocumentosType', 'getDocumentosTypeService', true],
            'App\\Form\\GraduadoPersonalesOrigType' => ['privates', 'App\\Form\\GraduadoPersonalesOrigType', 'getGraduadoPersonalesOrigTypeService', true],
            'App\\Form\\GraduadoPersonalesType' => ['privates', 'App\\Form\\GraduadoPersonalesType', 'getGraduadoPersonalesTypeService', true],
            'App\\Form\\GraduadoTitulacionesOrigType' => ['privates', 'App\\Form\\GraduadoTitulacionesOrigType', 'getGraduadoTitulacionesOrigTypeService', true],
            'App\\Form\\GraduadoTitulacionesType' => ['privates', 'App\\Form\\GraduadoTitulacionesType', 'getGraduadoTitulacionesTypeService', true],
            'App\\Form\\ImagenGraduadoOrigType' => ['privates', 'App\\Form\\ImagenGraduadoOrigType', 'getImagenGraduadoOrigTypeService', true],
            'App\\Form\\ImagenGraduadoType' => ['privates', 'App\\Form\\ImagenGraduadoType', 'getImagenGraduadoTypeService', true],
            'App\\Form\\TitulacionesGraduadoType' => ['privates', 'App\\Form\\TitulacionesGraduadoType', 'getTitulacionesGraduadoTypeService', true],
            'App\\Form\\TitulosType' => ['privates', 'App\\Form\\TitulosType', 'getTitulosTypeService', true],
            'App\\Form\\UserBusquedaType' => ['privates', 'App\\Form\\UserBusquedaType', 'getUserBusquedaTypeService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['services', '.container.private.form.type.file', 'get_Container_Private_Form_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
            'App\\Form\\ArchivosOrigType' => '?',
            'App\\Form\\ArchivosType' => '?',
            'App\\Form\\CarrerasType' => '?',
            'App\\Form\\DatosAcademicosOrigType' => '?',
            'App\\Form\\DatosAcademicosType' => '?',
            'App\\Form\\DatosAdministrativosOrigType' => '?',
            'App\\Form\\DatosAdministrativosType' => '?',
            'App\\Form\\DatosPersonalesOrigType' => '?',
            'App\\Form\\DatosPersonalesType' => '?',
            'App\\Form\\DocumentosType' => '?',
            'App\\Form\\GraduadoPersonalesOrigType' => '?',
            'App\\Form\\GraduadoPersonalesType' => '?',
            'App\\Form\\GraduadoTitulacionesOrigType' => '?',
            'App\\Form\\GraduadoTitulacionesType' => '?',
            'App\\Form\\ImagenGraduadoOrigType' => '?',
            'App\\Form\\ImagenGraduadoType' => '?',
            'App\\Form\\TitulacionesGraduadoType' => '?',
            'App\\Form\\TitulosType' => '?',
            'App\\Form\\UserBusquedaType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.data_collector'] ?? $container->load('getForm_TypeExtension_Form_DataCollectorService'));
        }, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ?? ($container->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ?? ($container->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($container->privates['data_collector.form'] ?? $container->getDataCollector_FormService())));
    }
}
