<?php

namespace ContainerZxDrT0I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImagenGraduadoTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ImagenGraduadoType' shared autowired service.
     *
     * @return \App\Form\ImagenGraduadoType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ImagenGraduadoType.php';

        return $container->privates['App\\Form\\ImagenGraduadoType'] = new \App\Form\ImagenGraduadoType();
    }
}
