<?php

namespace ContainerZxDrT0I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserBusquedaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LvaNcPg.App\Entity\UserBusqueda' shared service.
     *
     * @return \App\Entity\UserBusqueda
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.LvaNcPg": it references class "App\\Entity\\UserBusqueda" but no such service exists.');
    }
}
