<?php

namespace Container4WAxEge;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LvaNcPgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LvaNcPg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LvaNcPg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'busqueda' => ['privates', '.errored..service_locator.LvaNcPg.App\\Entity\\UserBusqueda', NULL, 'Cannot autowire service ".service_locator.LvaNcPg": it references class "App\\Entity\\UserBusqueda" but no such service exists.'],
        ], [
            'busqueda' => 'App\\Entity\\UserBusqueda',
        ]);
    }
}
