<?php

namespace Container4WAxEge;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTitulosTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TitulosType' shared autowired service.
     *
     * @return \App\Form\TitulosType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TitulosType.php';

        return $container->privates['App\\Form\\TitulosType'] = new \App\Form\TitulosType();
    }
}
