<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Graduado extends \App\Entity\Graduado implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'apellido', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'documentoIdentidad', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'nacionalidad', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'ciudad', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'provincia', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'calle', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'numeroCalle', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'piso', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'depto', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'tipoDocumentoIdentidad', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'fechaNacimiento', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'nroME', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'nroUnraf', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'fechaEgreso', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'imagenTED', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'titulaciones', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'fechaCreacion'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'apellido', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'documentoIdentidad', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'nacionalidad', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'ciudad', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'provincia', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'calle', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'numeroCalle', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'piso', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'depto', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'tipoDocumentoIdentidad', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'fechaNacimiento', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'nroME', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'nroUnraf', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'fechaEgreso', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'imagenTED', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'titulaciones', '' . "\0" . 'App\\Entity\\Graduado' . "\0" . 'fechaCreacion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Graduado $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', []);

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido(string $apellido): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', [$apellido]);

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoIdentidad(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoIdentidad', []);

        return parent::getDocumentoIdentidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoIdentidad(string $documentoIdentidad): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoIdentidad', [$documentoIdentidad]);

        return parent::setDocumentoIdentidad($documentoIdentidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getNacionalidad(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNacionalidad', []);

        return parent::getNacionalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setNacionalidad(string $nacionalidad): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNacionalidad', [$nacionalidad]);

        return parent::setNacionalidad($nacionalidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', []);

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad(string $ciudad): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', [$ciudad]);

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', []);

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia(string $provincia): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', [$provincia]);

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalle', []);

        return parent::getCalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalle(string $calle): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalle', [$calle]);

        return parent::setCalle($calle);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCalle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCalle', []);

        return parent::getNumeroCalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCalle(string $numeroCalle): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCalle', [$numeroCalle]);

        return parent::setNumeroCalle($numeroCalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPiso(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPiso', []);

        return parent::getPiso();
    }

    /**
     * {@inheritDoc}
     */
    public function setPiso(string $piso): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPiso', [$piso]);

        return parent::setPiso($piso);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepto', []);

        return parent::getDepto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepto(string $depto): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepto', [$depto]);

        return parent::setDepto($depto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono(string $telefono): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDocumentoIdentidad(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDocumentoIdentidad', []);

        return parent::getTipoDocumentoIdentidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDocumentoIdentidad(string $tipoDocumentoIdentidad): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDocumentoIdentidad', [$tipoDocumentoIdentidad]);

        return parent::setTipoDocumentoIdentidad($tipoDocumentoIdentidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', []);

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento(\DateTimeInterface $fechaNacimiento): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', [$fechaNacimiento]);

        return parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo(?string $titulo): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroME(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroME', []);

        return parent::getNroME();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroME(?string $nroME): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroME', [$nroME]);

        return parent::setNroME($nroME);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroUnraf(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroUnraf', []);

        return parent::getNroUnraf();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroUnraf(?string $nroUnraf): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroUnraf', [$nroUnraf]);

        return parent::setNroUnraf($nroUnraf);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEgreso(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEgreso', []);

        return parent::getFechaEgreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEgreso(?\DateTimeInterface $fechaEgreso): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEgreso', [$fechaEgreso]);

        return parent::setFechaEgreso($fechaEgreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenTED(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenTED', []);

        return parent::getImagenTED();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagenTED(?string $imagenTED): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagenTED', [$imagenTED]);

        return parent::setImagenTED($imagenTED);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulaciones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulaciones', []);

        return parent::getTitulaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function addTitulacione(\App\Entity\TitulacionesAlcanzadas $titulacione): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTitulacione', [$titulacione]);

        return parent::addTitulacione($titulacione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTitulacione(\App\Entity\TitulacionesAlcanzadas $titulacione): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTitulacione', [$titulacione]);

        return parent::removeTitulacione($titulacione);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', []);

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion(?\DateTimeInterface $fechaCreacion): \App\Entity\Graduado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', [$fechaCreacion]);

        return parent::setFechaCreacion($fechaCreacion);
    }

}
