<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4WAxEge\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4WAxEge/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4WAxEge.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4WAxEge\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4WAxEge\App_KernelDevDebugContainer([
    'container.build_hash' => '4WAxEge',
    'container.build_id' => '1d14f14b',
    'container.build_time' => 1620060695,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4WAxEge');
