<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB4HxiRl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB4HxiRl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB4HxiRl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB4HxiRl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB4HxiRl\App_KernelDevDebugContainer([
    'container.build_hash' => 'B4HxiRl',
    'container.build_id' => '6e0977a6',
    'container.build_time' => 1621256781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB4HxiRl');
